name: flutter_typed_navigation
description: A typed navigation framework for Flutter with hierarchical routing and state management support.
version: 0.1.0
homepage: https://github.com/your-username/flutter_typed_navigation

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.7
  freezed: ^2.5.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  # テスト用依存関係
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_typed_navigation
        pluginClass: FlutterTypedNavigationPlugin
      ios:
        pluginClass: FlutterTypedNavigationPlugin